# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\";\n\x0eNewGameRequest\x12\x0e\n\x06size_x\x18\x01 \x01(\x05\x12\x0e\n\x06size_y\x18\x02 \x01(\x05\x12\t\n\x01p\x18\x03 \x01(\x02\"\x1c\n\x0cNewGameReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x16ShowAllSessionsRequest\"f\n\x13SessionDetailsReply\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\x12\r\n\x05steps\x18\x04 \x01(\x05\x12\x0c\n\x04last\x18\x05 \x01(\t\"\x1a\n\x18GetCurrentSessionRequest\".\n\x18SetCurrentSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x1f\n\x0fGetStateRequest\x12\x0c\n\x04step\x18\x01 \x01(\x05\"\x1d\n\rGetStateReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\r\n\x0bStepRequest\"\x0b\n\tStepReply2\xcd\x03\n\x04Game\x12\x35\n\x07NewGame\x12\x14.game.NewGameRequest\x1a\x12.game.NewGameReply\"\x00\x12N\n\x0fShowAllSessions\x12\x1c.game.ShowAllSessionsRequest\x1a\x19.game.SessionDetailsReply\"\x00\x30\x01\x12P\n\x11GetCurrentSession\x12\x1e.game.GetCurrentSessionRequest\x1a\x19.game.SessionDetailsReply\"\x00\x12P\n\x11SetCurrentSession\x12\x1e.game.SetCurrentSessionRequest\x1a\x19.game.SessionDetailsReply\"\x00\x12\x38\n\x08GetState\x12\x15.game.GetStateRequest\x1a\x13.game.GetStateReply\"\x00\x12,\n\x04Step\x12\x11.game.StepRequest\x1a\x0f.game.StepReply\"\x00\x12\x32\n\x08SayHello\x12\x12.game.HelloRequest\x1a\x10.game.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWGAMEREQUEST']._serialized_start=20
  _globals['_NEWGAMEREQUEST']._serialized_end=79
  _globals['_NEWGAMEREPLY']._serialized_start=81
  _globals['_NEWGAMEREPLY']._serialized_end=109
  _globals['_HELLOREQUEST']._serialized_start=111
  _globals['_HELLOREQUEST']._serialized_end=139
  _globals['_HELLOREPLY']._serialized_start=141
  _globals['_HELLOREPLY']._serialized_end=170
  _globals['_SHOWALLSESSIONSREQUEST']._serialized_start=172
  _globals['_SHOWALLSESSIONSREQUEST']._serialized_end=196
  _globals['_SESSIONDETAILSREPLY']._serialized_start=198
  _globals['_SESSIONDETAILSREPLY']._serialized_end=300
  _globals['_GETCURRENTSESSIONREQUEST']._serialized_start=302
  _globals['_GETCURRENTSESSIONREQUEST']._serialized_end=328
  _globals['_SETCURRENTSESSIONREQUEST']._serialized_start=330
  _globals['_SETCURRENTSESSIONREQUEST']._serialized_end=376
  _globals['_GETSTATEREQUEST']._serialized_start=378
  _globals['_GETSTATEREQUEST']._serialized_end=409
  _globals['_GETSTATEREPLY']._serialized_start=411
  _globals['_GETSTATEREPLY']._serialized_end=440
  _globals['_STEPREQUEST']._serialized_start=442
  _globals['_STEPREQUEST']._serialized_end=455
  _globals['_STEPREPLY']._serialized_start=457
  _globals['_STEPREPLY']._serialized_end=468
  _globals['_GAME']._serialized_start=471
  _globals['_GAME']._serialized_end=932
# @@protoc_insertion_point(module_scope)
